import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../styles/globals.css';
import ApolloWrapper from '@/providers/apollo-provider';
import { Toaster } from 'sonner';
import TanStackProvider from '@/providers/tanstack-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full">
      <ApolloWrapper>
        <TanStackProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} 
          antialiased w-full h-full bg-zinc-100`}
          >
            {children}
            <Toaster position="top-center" />
          </body>
        </TanStackProvider>
      </ApolloWrapper>
    </html>
  );
}

/**
 * I'm using 2 providers, one for graphql and other for rest
 *
 * Graphql:
 *  ApolloClient
 *
 * Rest:
 *  TanTanStack
 *
 */
